### ISSUE TITLE
Add i18n support.

### ISSUE THREAD

**Issue by nserrino** [pixie-labs/pixie-docs#4]
Context from @NickLanam:

The good news is that it's not all that hard to do since the blog/website/docs are already using Gatsby. 

https://www.gatsbyjs.com/plugins/gatsby-plugin-react-i18next/

This library makes it pretty straightforward to annotate all of the hardcoded strings we have (or replace them with identifiers - it's flexible). Then add translation files for the first language/locale we want to support, being en-us obviously... and Gatsby can handle the rest outside of a language selector.

Article-like content (blog articles, prose in the docs, some sections of the main website) are a bit different but can be handled about as easily.

Kubernetes does this: https://github.com/feiskyer/kubernetes-docs/tree/master/content 
https://kubernetes.io/docs/contribute/localization/#translating-content

**Comment by htroisi** [comment]
Fixed by #34.
